
"""
Django settings for football project.

Generated by 'django-admin startproject' using Django 5.0.3.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url


# ============================================================
# BASE DIRECTORY / ENVIRONMENT
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root
load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv("SECRET_KEY", "")

DEBUG = os.getenv("DEBUG", "False").lower() in (
    "true",
    "1",
    "yes",
)

ALLOWED_HOSTS = [
    "futbollal.com",
    "www.futbollal.com",
    "127.0.0.1",
    "localhost",
]


# ============================================================
# API KEYS
# ============================================================

FOOTBALL_API = os.getenv("FOOTBALL_API")
NEWS_API = os.getenv("NEWS_API")
RAPID_API = os.getenv("RAPID_API_KEY")

S_ALL_SPORT_API = os.getenv("ALL_SPORT_API")

FOOTBALL_LIVE_STREAMING_API = os.getenv(
    "FOOTBALL_LIVE_STREAMING_API"
)

TRANSFER_NEWS_API = os.getenv("TRANSFER_NEWS_API")

BIGBALLS_API_KEY = os.getenv("BIGBALLS_API_KEY")


# ============================================================
# STRIPE
# ============================================================

# Local / Stripe TEST mode
STRIPE_SECRET_KEY_TEST = os.getenv(
    "STRIPE_SECRET_KEY_TEST",
    ""
)

STRIPE_PUBLISHABLE_KEY_TEST = os.getenv(
    "STRIPE_PUBLISHABLE_KEY_TEST",
    ""
)

STRIPE_WEBHOOK_SECRET_TEST = os.getenv(
    "STRIPE_WEBHOOK_SECRET_TEST",
    ""
)

STRIPE_RECURRING_PRICE_ID_TEST = os.getenv(
    "STRIPE_RECURRING_PRICE_ID_TEST",
    ""
)

STRIPE_ONE_TIME_PRICE_ID_TEST = os.getenv(
    "STRIPE_ONE_TIME_PRICE_ID_TEST",
    ""
)


# Production / LIVE Stripe
STRIPE_SECRET_KEY = os.getenv(
    "STRIPE_SECRET_KEY",
    ""
)

STRIPE_PUBLISHABLE_KEY = os.getenv(
    "STRIPE_PUBLISHABLE_KEY",
    ""
)

STRIPE_WEBHOOK_SECRET = os.getenv(
    "STRIPE_WEBHOOK_SECRET",
    ""
)

STRIPE_RECURRING_PRICE_ID = os.getenv(
    "STRIPE_RECURRING_PRICE_ID",
    ""
)

STRIPE_ONE_TIME_PRICE_ID = os.getenv(
    "STRIPE_ONE_TIME_PRICE_ID",
    ""
)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "daphne",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "channels",

    "blog",
    "news",
    "rapid",
    "live_stream_api",
    "register",
    "index",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django_ratelimit.middleware.RatelimitMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / APPLICATION CONFIGURATION
# ============================================================

ROOT_URLCONF = "football.urls"

ASGI_APPLICATION = "football.asgi.application"

WSGI_APPLICATION = "football.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

# Railway / production:
#
# Set:
#
# DATABASE_URL=postgresql://...
#
# or your existing:
#
# DRINI_SQL=postgresql://...
#
# Local:
# SQLite is used when no database URL exists.

DATABASE_URL = os.getenv("DATABASE_URL")
DRINI_SQL = os.getenv("DRINI_SQL")


DATABASE_URL_TO_USE = DATABASE_URL or DRINI_SQL


if DATABASE_URL_TO_USE:

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL_TO_USE,
            conn_max_age=600,
        )
    }

else:

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ============================================================
# REDIS
# ============================================================

REDIS_URL = os.getenv("REDIS_URL")


if REDIS_URL:

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",

            "LOCATION": REDIS_URL,

            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",

                "IGNORE_EXCEPTIONS": True,

                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 50,
                },
            },

            "KEY_PREFIX": "futbollal",
        }
    }

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",

            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        }
    }

else:

    # Local development without Redis

    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends.locmem.LocMemCache"
            ),
            "LOCATION": "futbollal-local-cache",
        }
    }

    # Local Channels backend
    # This allows Django/Channels to run without Redis.

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": (
                "channels.layers.InMemoryChannelLayer"
            ),
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation."
        "MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation."
        "CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation."
        "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Tirane"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# WHITE NOISE
# ============================================================

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },

    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# ============================================================
# SECURITY / HTTPS
# ============================================================

if not DEBUG:

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

else:

    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "https://futbollal.com",
    "https://www.futbollal.com",
    "https://*.railway.app",
]


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

