# Generated by Django 5.0.7 on 2026-09-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentView',
        ),
    ]
